import React, { useState } from 'react';
import { Table2 } from 'lucide-react';
import DropZone from '../common/DropZone';
import DownloadScreen from '../common/DownloadScreen';

function csvEscape(value) { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }

export default function ExtractTableTool() {
  const [file, setFile] = useState(null); const [thumbs, setThumbs] = useState([]); const [pages, setPages] = useState('');
  const [tables, setTables] = useState([]); const [busy, setBusy] = useState(false); const [previewBusy, setPreviewBusy] = useState(false); const [message, setMessage] = useState(''); const [downloadUrl, setDownloadUrl] = useState('');
  async function choose(files) { const picked = files[0]; if (!picked) return; setFile(picked); setTables([]); setPreviewBusy(true); setMessage('กำลังสร้างตัวอย่างหน้า PDF…'); const body = new FormData(); body.append('file', picked); try { const res = await fetch('/api/pdf-thumbnails', { method:'POST', body }); if (!res.ok) throw new Error(await res.text()); const data = await res.json(); setThumbs(data.thumbnails || []); setMessage('เลือกหน้าที่มีตาราง แล้วกดดึงตาราง'); } catch (e) { setMessage(`สร้างตัวอย่างไม่สำเร็จ: ${e.message}`); } finally { setPreviewBusy(false); } }
  async function extract(e) { e.preventDefault(); if (!file || busy) return; setBusy(true); setMessage('กำลังวิเคราะห์ตาราง…'); const body = new FormData(); body.append('file', file); if (pages.trim()) body.append('pages', pages.trim()); try { const res = await fetch('/api/extract-table', { method:'POST', body }); if (!res.ok) throw new Error(await res.text()); const data = await res.json(); setTables(data.tables || []); setMessage(data.count ? `พบ ${data.count} ตาราง ตรวจสอบข้อมูลก่อนดาวน์โหลด` : 'ไม่พบตารางในหน้าที่เลือก'); } catch (e) { setMessage(`ดึงตารางไม่สำเร็จ: ${e.message}`); } finally { setBusy(false); } }
  function openDownload() { const rows = tables.flatMap((item) => item.rows); const csv = rows.map((row) => row.map(csvEscape).join(',')).join('\n'); setDownloadUrl(URL.createObjectURL(new Blob([`\ufeff${csv}`], { type:'text/csv;charset=utf-8' }))); }
  if (downloadUrl) return <DownloadScreen downloadUrl={downloadUrl} filename="extracted-tables.csv" title="ดึงตารางเรียบร้อยแล้ว" subtitle="ตรวจสอบผลลัพธ์แล้ว ดาวน์โหลดไฟล์ CSV ได้จากหน้านี้" onBack={() => { URL.revokeObjectURL(downloadUrl); setDownloadUrl(''); }} onReset={() => { URL.revokeObjectURL(downloadUrl); setDownloadUrl(''); setTables([]); setFile(null); setThumbs([]); }} />;
  return <div className="panel extract-table-panel"><form onSubmit={extract} className="tool-controls"><DropZone onFilesSelected={choose} label={file ? file.name : 'ลาก PDF มาวาง หรือเลือกไฟล์'} />{previewBusy && <p>กำลังสร้าง preview…</p>}{thumbs.length > 0 && <section className="table-page-preview"><div className="image-preview-header"><strong>ตัวอย่างหน้าเอกสาร</strong><span>เลือกหน้าที่มีตาราง</span></div><div className="image-thumb-grid">{thumbs.map((src, i) => { const page=i+1; const selected=pages.split(',').map(v=>v.trim()).includes(String(page)); return <button type="button" key={page} className={`image-thumb ${selected ? 'selected' : ''}`} onClick={() => { const set=new Set(pages.split(',').map(v=>v.trim()).filter(Boolean)); set.has(String(page)) ? set.delete(String(page)) : set.add(String(page)); setPages([...set].sort((a,b)=>Number(a)-Number(b)).join(',')); }}><img src={src} alt={`หน้า ${page}`} /><span>หน้า {page}</span></button>; })}</div></section>}<label>หน้าที่จะตรวจตาราง (เว้นว่าง = ทุกหน้า)<input value={pages} onChange={(e)=>setPages(e.target.value)} placeholder="เช่น 1-3, 5" /></label><button className="primary" type="submit" disabled={!file||busy}><Table2 size={17}/> {busy ? 'กำลังดึงตาราง…' : 'ดึงตาราง'}</button>{tables.length > 0 && <section className="extract-table-result"><div className="extract-text-head"><strong>ผลลัพธ์ตรวจสอบได้ก่อนดาวน์โหลด</strong><button type="button" className="button small secondary" onClick={openDownload}>ตรวจสอบเสร็จ ไปหน้าดาวน์โหลด</button></div>{tables.map((item, index) => <div className="table-result" key={`${item.page}-${index}`}><small>หน้า {item.page} · ตาราง {item.table}</small><div className="table-scroll"><table><tbody>{item.rows.map((row, r) => <tr key={r}>{row.map((cell, c) => <td key={c} contentEditable suppressContentEditableWarning>{cell}</td>)}</tr>)}</tbody></table></div></div>)}</section>}{message && <p className="message">{message}</p>}</form></div>;
}
