import React, { useState } from 'react';
import { FilePlus2, GripVertical } from 'lucide-react';
import DownloadScreen from '../common/DownloadScreen';

export default function ImagePdfTool() {
  const [files, setFiles] = useState([]); const [busy, setBusy] = useState(false); const [result, setResult] = useState(''); const [message, setMessage] = useState('');
  const addFiles = (event) => { const incoming = [...event.target.files].filter((file) => file.type.startsWith('image/')); setFiles((current) => [...current, ...incoming]); event.target.value = ''; };
  const remove = (index) => setFiles((current) => current.filter((_, i) => i !== index));
  const move = (from, to) => setFiles((current) => { const next = [...current]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; });
  async function convert(event) { event.preventDefault(); if (!files.length || busy) return; setBusy(true); setMessage('กำลังรวมภาพเป็น PDF…'); const body = new FormData(); files.forEach((file) => body.append('files', file)); try { const response = await fetch('/api/images-to-pdf', { method: 'POST', body }); if (!response.ok) throw new Error(await response.text()); setResult(URL.createObjectURL(await response.blob())); setMessage(''); } catch (error) { setMessage(`สร้าง PDF ไม่สำเร็จ: ${error.message}`); } finally { setBusy(false); } }
  if (result) return <DownloadScreen downloadUrl={result} filename="images.pdf" title="สร้าง PDF จากรูปเรียบร้อยแล้ว" onReset={() => { URL.revokeObjectURL(result); setResult(''); }} />;
  return <div className="panel image-pdf-panel"><form onSubmit={convert} className="tool-controls"><label className="drop"><FilePlus2 size={26} /><span>เลือกหรือเพิ่มรูปภาพ</span><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={addFiles} /><em>{files.length ? `เลือกแล้ว ${files.length} รูป` : 'PNG, JPG หรือ WebP'}</em></label>{files.length > 0 && <div className="image-pdf-review"><div className="image-preview-header"><strong>ตรวจสอบลำดับรูปก่อนสร้าง PDF</strong><button type="button" className="button small secondary" onClick={() => setFiles([])}>ล้างทั้งหมด</button></div><div className="image-thumb-grid">{files.map((file, index) => <article className="image-pdf-card" key={`${file.name}-${file.lastModified}-${index}`}><GripVertical size={15} /><img src={URL.createObjectURL(file)} alt={`หน้า ${index + 1}`} /><strong>หน้า {index + 1}</strong><small>{file.name}</small><div><button type="button" disabled={index === 0} onClick={() => move(index, index - 1)}>←</button><button type="button" disabled={index === files.length - 1} onClick={() => move(index, index + 1)}>→</button><button type="button" onClick={() => remove(index)}>ลบ</button></div></article>)}</div></div>}<button className="primary" type="submit" disabled={!files.length || busy}>{busy ? 'กำลังสร้าง…' : 'สร้าง PDF จากรูป'}</button>{message && <p className="message">{message}</p>}</form></div>;
}
