import React, { useMemo, useState } from 'react';
import DropZone from '../common/DropZone';
import DownloadScreen from '../common/DownloadScreen';

export default function InsertPageTool() {
  const [file, setFile] = useState(null), [thumbs, setThumbs] = useState([]), [sourceFile, setSourceFile] = useState(null), [sourceThumbs, setSourceThumbs] = useState([]), [sourcePages, setSourcePages] = useState([]), [count, setCount] = useState(1), [position, setPosition] = useState(1), [step, setStep] = useState('select'), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [resultUrl, setResultUrl] = useState('');
  const loadThumbs = async (picked) => { const body = new FormData(); body.append('file', picked); const response = await fetch('/api/pdf-thumbnails', { method: 'POST', body }); if (!response.ok) throw new Error(await response.text()); return (await response.json()).thumbnails || []; };
  const chooseTarget = async (files) => { const picked = files[0]; if (!picked) return; try { setFile(picked); setThumbs(await loadThumbs(picked)); setStep('configure'); setMessage(''); } catch (error) { setMessage(`สร้างตัวอย่างไม่สำเร็จ: ${error.message}`); } };
  const chooseSource = async (files) => { const picked = files[0]; if (!picked) return; try { setSourceFile(picked); setSourceThumbs(await loadThumbs(picked)); setSourcePages([]); setMessage(''); } catch (error) { setMessage(`อ่านไฟล์ที่จะแทรกไม่สำเร็จ: ${error.message}`); } };
  const usingSource = Boolean(sourceFile);
  const inserted = usingSource ? sourcePages.slice().sort((a, b) => a - b).map((page) => ({ src: sourceThumbs[page - 1], label: `แทรกหน้า ${page}` })) : Array.from({ length: Number(count) || 0 }, (_, index) => ({ blank: true, label: `หน้าใหม่ ${index + 1}` }));
  const preview = useMemo(() => { const base = thumbs.map((src, index) => ({ src, label: `หน้า ${index + 1}` })); return [...base.slice(0, position - 1), ...inserted, ...base.slice(position - 1)]; }, [thumbs, position, inserted.length, sourcePages.join(',')]);
  const toggle = (page) => setSourcePages((current) => current.includes(page) ? current.filter((item) => item !== page) : [...current, page]);
  async function process(event) { event.preventDefault(); if (!file || busy || (usingSource && !sourcePages.length)) return; setBusy(true); const body = new FormData(); body.append('file', file); body.append('count', usingSource ? '0' : count); body.append('position', position); if (usingSource) { body.append('source_file', sourceFile); body.append('pages', sourcePages.slice().sort((a, b) => a - b).join(',')); } try { const response = await fetch('/api/insert-pages', { method: 'POST', body }); if (!response.ok) throw new Error(await response.text()); setResultUrl(URL.createObjectURL(await response.blob())); setStep('download'); } catch (error) { setMessage(`แทรกหน้าไม่สำเร็จ: ${error.message}`); } finally { setBusy(false); } }
  if (step === 'download' && resultUrl) return <DownloadScreen downloadUrl={resultUrl} filename={`pages-inserted_${file?.name || 'document.pdf'}`} title="แทรกหน้า PDF สำเร็จแล้ว!" subtitle={usingSource ? `แทรกจากไฟล์ ${sourceFile.name} จำนวน ${sourcePages.length} หน้า` : `เพิ่มหน้าเปล่า ${count} หน้า`} onBack={() => setStep('configure')} backLabel="← กลับไปตั้งค่า" onReset={() => { setStep('select'); setFile(null); setThumbs([]); setSourceFile(null); setSourceThumbs([]); setSourcePages([]); setResultUrl(''); }} resetLabel="แทรกหน้าไฟล์ใหม่" />;
  return <div className="panel"><p className="merge-step">{step === 'select' ? '01 / เลือกเอกสารหลัก' : '02 / เลือกหน้าและดูตัวอย่าง'}</p>{step === 'select' ? <div className="tool-controls"><DropZone onFilesSelected={chooseTarget} label="ลาก PDF หลักมาวาง หรือเลือกไฟล์" /><p className="hint">เลือกเอกสารหลักที่ต้องการแทรกหน้าเข้าไป</p>{message && <p className="message">{message}</p>}</div> : <form onSubmit={process} className="tool-controls"><button type="button" className="back" onClick={() => setStep('select')}>← กลับไปเปลี่ยนไฟล์หลัก</button><DropZone onFilesSelected={chooseSource} label={sourceFile ? sourceFile.name : 'ลาก PDF อื่นมาวาง หรือเลือกไฟล์'} hintText="เพิ่มหน้าจาก PDF อื่น (ไม่เลือกก็แทรกหน้าเปล่าได้)" /><div className="insert-page-settings"><label>แทรกก่อนหน้าที่<input type="number" min="1" max={thumbs.length + 1} value={position} onChange={(event) => setPosition(Math.min(thumbs.length + 1, Math.max(1, Number(event.target.value) || 1)))} /><small>ใส่ {thumbs.length + 1} เพื่อแทรกต่อท้าย</small></label>{!usingSource && <label>จำนวนหน้าเปล่า<input type="number" min="1" max="20" value={count} onChange={(event) => setCount(Math.max(1, Number(event.target.value) || 1))} /></label>}</div>{usingSource && <div className="image-page-preview"><div className="image-preview-header"><strong>เลือกหน้าจาก PDF ที่จะแทรก</strong><span>เลือกแล้ว {sourcePages.length} หน้า</span></div><div className="image-thumb-grid">{sourceThumbs.map((src, index) => { const page = index + 1; return <button type="button" key={page} className={`image-thumb ${sourcePages.includes(page) ? 'selected' : ''}`} onClick={() => toggle(page)}><img src={src} alt={`หน้า ${page}`} /><span>{sourcePages.includes(page) ? '✓ ' : ''}หน้า {page}</span></button>; })}</div></div>}<div className="image-page-preview"><div className="image-preview-header"><strong>ตัวอย่างผลลัพธ์ก่อนประมวลผล</strong><span>{preview.length} หน้า</span></div><div className="image-thumb-grid">{preview.map((item, index) => <div className={`image-thumb ${item.blank ? 'insert-page-blank' : 'selected'}`} key={`${item.label}-${index}`}>{item.blank ? <div className="insert-page-blank-icon">＋</div> : <img src={item.src} alt={item.label} />}<span>{item.label}</span></div>)}</div></div><button className="primary" type="submit" disabled={busy || (usingSource && !sourcePages.length)}>{busy ? 'กำลังแทรกหน้า…' : 'ยืนยันและสร้าง PDF'}</button>{message && <p className="message">{message}</p>}</form>}</div>;
}
