import React, { useState, useRef } from 'react';
import { Eraser } from 'lucide-react';
import DropZone from '../common/DropZone';
import DownloadScreen from '../common/DownloadScreen';

export default function RedactTool() {
  const [file, setFile] = useState(null); const [thumbs, setThumbs] = useState([]); const [page, setPage] = useState(1); const [regions, setRegions] = useState([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [downloadUrl, setDownloadUrl] = useState(''); const [draft, setDraft] = useState(null); const imageRef = useRef(null); const drag = useRef(null);
  async function choose(files) { const picked=files[0]; if(!picked)return; setFile(picked); setRegions([]); setMessage('กำลังสร้างตัวอย่างหน้า PDF…'); const body=new FormData(); body.append('file',picked); try { const r=await fetch('/api/pdf-thumbnails',{method:'POST',body}); if(!r.ok)throw new Error(await r.text()); const d=await r.json(); setThumbs(d.thumbnails||[]); setMessage('เลือกหน้า แล้วลากกรอบทับข้อมูลที่ต้องการลบ'); } catch(e){setMessage(`สร้างตัวอย่างไม่สำเร็จ: ${e.message}`);} }
  function point(e){const r=imageRef.current?.getBoundingClientRect(); if(!r)return null; return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
  function start(e){const p=point(e);if(!p)return; e.currentTarget.setPointerCapture?.(e.pointerId); drag.current=p; setDraft({page,...p,width:0,height:0});}
  function move(e){if(!drag.current)return;const p=point(e);if(!p)return;const a=drag.current;setDraft({page,x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(p.x-a.x),height:Math.abs(p.y-a.y)});}
  function finish(e){if(!drag.current)return;const p=point(e);if(!p)return;const a=drag.current;const box={page,x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(p.x-a.x),height:Math.abs(p.y-a.y)};if(box.width>.01&&box.height>.01)setRegions(v=>[...v,box]);drag.current=null;setDraft(null);}
  async function submit(e){e.preventDefault();if(!file||!regions.length||busy)return;setBusy(true);setMessage('กำลังลบข้อมูลออกจาก PDF…');const body=new FormData();body.append('file',file);body.append('regions',JSON.stringify(regions));try{const r=await fetch('/api/redact',{method:'POST',body});if(!r.ok)throw new Error(await r.text());setDownloadUrl(URL.createObjectURL(await r.blob()));setMessage('');}catch(err){setMessage(`ประมวลผลไม่สำเร็จ: ${err.message}`);}finally{setBusy(false);}}
  function reset(){if(downloadUrl)URL.revokeObjectURL(downloadUrl);setDownloadUrl('');setFile(null);setThumbs([]);setRegions([]);}
  function undo(){setRegions(v=>v.slice(0,-1));}
  function clearPage(){setRegions(v=>v.filter(box=>box.page!==page));}
  if(downloadUrl)return <DownloadScreen downloadUrl={downloadUrl} filename="redacted.pdf" title="ลบข้อมูลลับเรียบร้อยแล้ว" subtitle="ข้อมูลที่อยู่ในกรอบถูกปิดทับลงในไฟล์ผลลัพธ์แล้ว" onReset={reset}/>;
  const current=regions.filter(v=>v.page===page);
  return <div className="panel redact-tool-panel"><form onSubmit={submit} className="tool-controls"><DropZone onFilesSelected={choose} label={file?file.name:'ลาก PDF มาวาง หรือเลือกไฟล์'}/>{thumbs.length>0&&<><div className="image-page-preview"><div className="image-preview-header"><strong>ตัวอย่างหน้าเอกสาร</strong><span>หน้าที่ {page} · กรอบที่วาง {regions.length}</span></div><div className="redact-actions redact-actions-top"><button type="button" className="button small secondary" onClick={undo} disabled={!regions.length}>↶ Undo / ย้อนกลับกรอบล่าสุด</button><button type="button" className="button small secondary" onClick={clearPage} disabled={!current.length}>ล้างกรอบหน้านี้</button></div><div className="redact-canvas" onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}><img ref={imageRef} src={thumbs[page-1]} alt={`หน้า ${page}`} draggable="false"/>{current.map((box,i)=><span key={i} className="redact-box" style={{left:`${box.x*100}%`,top:`${box.y*100}%`,width:`${box.width*100}%`,height:`${box.height*100}%`}}/> )}{draft&&<span className="redact-box draft" style={{left:`${draft.x*100}%`,top:`${draft.y*100}%`,width:`${draft.width*100}%`,height:`${draft.height*100}%`}}/>}</div><div className="redact-pages">{thumbs.map((src,i)=><button type="button" key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>หน้า {i+1}</button>)}</div></div><p className="hint">ลากเมาส์บนภาพเพื่อสร้างกรอบสีดำ กรอบจะแสดงทันทีขณะลาก เพิ่มได้หลายกรอบและหลายหน้า</p></>}<button className="primary" type="submit" disabled={!file||!regions.length||busy}><Eraser size={17}/>{busy?'กำลังประมวลผล…':'ลบข้อมูลในกรอบ'}</button>{message&&<p className="message">{message}</p>}</form></div>;
}
