import React, { useState } from 'react';
import { Lock, Unlock } from 'lucide-react';
import DropZone from '../common/DropZone';
import DownloadScreen from '../common/DownloadScreen';

export default function SecurityTool({ mode = 'protect' }) {
  const protecting = mode === 'protect';
  const [file, setFile] = useState(null); const [thumbs, setThumbs] = useState([]); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [downloadUrl, setDownloadUrl] = useState('');
  async function choose(files) { const picked = files[0]; if (!picked) return; setFile(picked); setMessage('กำลังสร้างตัวอย่างหน้า PDF…'); const body = new FormData(); body.append('file', picked); try { const res = await fetch('/api/pdf-thumbnails', { method:'POST', body }); if (!res.ok) throw new Error(await res.text()); setThumbs((await res.json()).thumbnails || []); setMessage('ตรวจสอบไฟล์แล้ว กรอกรหัสผ่านเพื่อดำเนินการ'); } catch (e) { setMessage(`สร้างตัวอย่างไม่สำเร็จ: ${e.message}`); } }
  async function submit(e) { e.preventDefault(); if (!file || !password || busy) return; if (protecting && password !== confirm) { setMessage('รหัสผ่านสองช่องไม่ตรงกัน'); return; } setBusy(true); setMessage(protecting ? 'กำลังตั้งรหัสผ่าน…' : 'กำลังถอดรหัส…'); const body = new FormData(); body.append('file', file); body.append('password', password); try { const res = await fetch(`/api/${mode}`, { method:'POST', body }); if (!res.ok) throw new Error(await res.text()); setDownloadUrl(URL.createObjectURL(await res.blob())); setMessage(''); } catch (e) { setMessage(`ดำเนินการไม่สำเร็จ: ${e.message}`); } finally { setBusy(false); } }
  function reset() { if (downloadUrl) URL.revokeObjectURL(downloadUrl); setDownloadUrl(''); setFile(null); setThumbs([]); setPassword(''); setConfirm(''); }
  if (downloadUrl) return <DownloadScreen downloadUrl={downloadUrl} filename={protecting ? 'protected.pdf' : 'unlocked.pdf'} title={protecting ? 'ตั้งรหัสผ่านเรียบร้อยแล้ว' : 'ถอดรหัส PDF เรียบร้อยแล้ว'} subtitle="ไฟล์พร้อมดาวน์โหลดและตรวจสอบตัวอย่างได้จากหน้านี้" onReset={reset} />;
  return <div className="panel security-tool-panel"><form onSubmit={submit} className="tool-controls"><DropZone onFilesSelected={choose} label={file ? file.name : 'ลาก PDF มาวาง หรือเลือกไฟล์'} />{thumbs.length > 0 && <section className="image-page-preview"><div className="image-preview-header"><strong>ตัวอย่างไฟล์ก่อนประมวลผล</strong><span>{thumbs.length} หน้า</span></div><div className="image-thumb-grid">{thumbs.map((src, i) => <div className="image-thumb selected" key={i}><img src={src} alt={`หน้า ${i + 1}`} /><span>หน้า {i + 1}</span></div>)}</div></section>}<label>รหัสผ่าน<input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="กรอกรหัสผ่าน" autoComplete="new-password" /></label>{protecting && <label>ยืนยันรหัสผ่าน<input type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} placeholder="กรอกรหัสผ่านอีกครั้ง" autoComplete="new-password" /></label>}<button className="primary" type="submit" disabled={!file||!password||busy}>{protecting ? <Lock size={17}/> : <Unlock size={17}/>} {busy ? 'กำลังประมวลผล…' : protecting ? 'ตั้งรหัสผ่าน PDF' : 'ถอดรหัส PDF'}</button>{message && <p className="message">{message}</p>}</form></div>;
}
